### ISSUE TITLE
vRA 8.12 Connect-VRAServer URI issue

### ISSUE THREAD

**Issue by bpfoley45** [jakkulabs/PowervRA#290] opened 2023-06-13 14:03 UTC
Steps to reproduce
------------------

Upgraded vRA to 8.12 and using PowervRA 5.20:

$creds = get-credential
Connect-vRAServer -Username $creds.usernerm -Password $creds.password -Server vra.domain.com -IgnoreCertRequirements 

Expected behavior
-----------------

Token acquired

Actual behavior
---------------

Invoke-RestMethod: {"headers":{},"body":{"timestamp":1686664173423,"type":"CLIENT_ERROR","status":"400 BAD_REQUEST","error":"Bad Request","serverMessage":"404 NOT_FOUND \"No matching handler\""},"statusCode":"BAD_REQUEST","statusCodeValue":400}

Extra
----------------

I found that changing line 495 in PowerVRA.psm1 from
$URI = "https://$($Server)/csp/gateway/am/idp/auth/login?access_token"
to
URI = "https://$($Server)/csp/gateway/am/api/login?access_token"

resolves the issue.

**Comment by tocano33** [comment] 2023-06-13 14:30
This appears to be a duplicate of Issue #287   and is fixed by pull request #288

**Comment by jonathanmedd** [comment] 2023-07-05 17:04
Fixed in #288

**Closed by jonathanmedd** 2023-07-05 17:04 UTC
Labels: bug, vRA 8.x+
