### ISSUE TITLE
FEATURE REQUEST: Remove Networkpath from reservation.

### ISSUE THREAD

**Issue by dteixeirars** [jakkulabs/PowervRA#43] opened 2016-06-28 19:34 UTC
Remove Networkpath from reservation.

**Comment by chelnak** [comment] 2016-06-29 07:12
This is on our roadmap but it's good that a feature request has been created.

The issue is the complexity of the reservation object that is returned from vRA.. it doesn't lend itself to easily removing the right network path without rebuilding the whole object.

If you have any ideas feel free to put them here!

Cheers

**Comment by chelnak** [comment] 2017-04-24 19:06
@dteixeirars This will be in release 2.2.0 👍

**Closed by chelnak** 2017-04-24 19:06 UTC
Labels: enhancement
